package net.bluecow.voicebus.core.userprefs;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "VoicebusDestination")
public class Destination {

    /**
     * The user who defined this destination, and the only user who can see it.
     */
    @DynamoDBHashKey
    private String userId;

    @DynamoDBRangeKey
    private String primaryName;

    @DynamoDBAutoGeneratedTimestamp
    private Date createdAt;

    @DynamoDBVersionAttribute
    private Long version;

    /**
     * Additional names given to this destination by the user.
     */
    private Set<String> synonyms;

    /**
     * The stops for which predictions should be given when the user wants to go to this destination.
     */
    private List<Stop> stops;

}
