package net.bluecow.voicebus.core.dialogflow;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDBTable(tableName = "VoicebusConversation")
public class Conversation {

    /**
     * The user who is having the conversation.
     */
    @DynamoDBHashKey
    private String userId;

    @DynamoDBAutoGeneratedTimestamp
    private Date createdAt;

    private Long expiresAt;

    @DynamoDBVersionAttribute
    private Long version;

    private String state;
}
